# A string used to distinguish different Supabase projects on the same host.
project_id = "env(SUPABASE_PROJECT_ID)"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[studio]
enabled = true
port = 54323
api_url = "env(SUPABASE_API_URL)"
openai_api_key = "env(OPENAI_API_KEY)"

[auth]
enabled = true
site_url = "env(SITE_URL)"
additional_redirect_urls = [
    "env(DEV_SITE_URL)",
    "env(SITE_URL)",
]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = true
enable_anonymous_sign_ins = false
enable_manual_linking = false
minimum_password_length = 6

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

[auth.email.template.confirmation]
subject = "You need to confirm your email!!"
content_path = "./supabase/templates/confirm-email.html"

[auth.email.smtp]
enabled = true
host = "env(SMTP_HOST)"
port = "env(SMTP_PORT)"
user = "env(SMTP_USER)"
pass = "env(SMTP_PASS)"
admin_email = "env(SMTP_FROM_EMAIL)"
sender_name = "env(SMTP_FROM_NAME)"

[auth.external.google]
enabled = true
client_id = "env(GOOGLE_OAUTH_CLIENT_ID)"
secret = "env(GOOGLE_OAUTH_CLIENT_SECRET)"
redirect_uri = "env(AUTH_REDIRECT_URL)"

[auth.external.azure]
enabled = true
client_id = "env(AZURE_AD_CLIENT_ID)"
secret = "env(AZURE_AD_CLIENT_SECRET)"
url = "env(AZURE_AD_TENANT_URL)"
redirect_uri = "env(AUTH_REDIRECT_URL)"

[db]
port = 54322
shadow_port = 54320
major_version = 15

# Declarative schema configuration
[db.migrations]
schema_paths = [
  "./schemas/*.sql",
]

[storage]
enabled = true
file_size_limit = "50MiB"

[analytics]
enabled = true
port = 54327
backend = "postgres"